/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.AdminPages;

import com.CustomCards.Model_Cards;
import com.DataHandler.InventoryHandler;
import com.DatabaseConnector.DatabaseConnector;
import com.pages.Frontpage;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author loena
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form practice1
     */
    public AdminPanel() {
        initComponents();
        /**
        * code for passing data to Cards
        */
            cards1.setData(new Model_Cards(new ImageIcon(getClass().getResource("/images/cards1.png")),"attendance","12345","total Attendance"));
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        Inventory.setVisible(false);
        Dashboard.setVisible(true);
        Attendance.setVisible(false);
        Borrowing.setVisible(false);

        tab2.setBackground(new Color(204, 204, 255)); // Slightly more opaque on click

        tab1.setBackground(new Color(102, 0, 255));
        tab3.setBackground(new Color(102, 0, 255));
        tab5.setBackground(new Color(102, 0, 255));

        labeltab2.setForeground(Color.black);
        labeltab1.setForeground(Color.white);
        labeltab3.setForeground(Color.white);
        labeltab4.setForeground(Color.white);

        // to add data to table
        try (Connection conn = DatabaseConnector.getConnection()) {
            String query = "SELECT * FROM inventorytable";
            PreparedStatement pstmt = conn.prepareStatement(query);
            ResultSet rs = pstmt.executeQuery();

            // Center text in the JTable cells
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            centerRenderer.setVerticalAlignment(SwingConstants.CENTER);

            while (rs.next()) {
                // User exists with the provided username and password
                String id = String.valueOf(rs.getInt("id"));
                String name = rs.getString("equipment_name");
                String quantity = String.valueOf(rs.getInt("quantity"));
                String category = rs.getString("category");

                //String array for store data into jtable
                String tbData[] = {id, name, quantity, category};

                DefaultTableModel tblModel = (DefaultTableModel) InventoryTable.getModel();

                //add Strinf array dara into table
                tblModel.addRow(tbData);

            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        labeltab1 = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        labeltab2 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        labeltab3 = new javax.swing.JLabel();
        tab5 = new javax.swing.JPanel();
        labeltab4 = new javax.swing.JLabel();
        tab6 = new javax.swing.JPanel();
        labeltab5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Borrowing = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Inventory = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        EquipmentTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        categoryCbx = new javax.swing.JComboBox<>();
        AddBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InventoryTable = new javax.swing.JTable();
        QuantityTf = new javax.swing.JSpinner();
        idTxt = new javax.swing.JTextField();
        Attendance = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Dashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cards1 = new com.CustomCards.Cards();
        cards2 = new com.CustomCards.Cards();
        cards3 = new com.CustomCards.Cards();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 0, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab1.setBackground(new java.awt.Color(102, 0, 255));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        labeltab1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        labeltab1.setText("Inventory");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(labeltab1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labeltab1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(tab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 220, 50));

        tab2.setBackground(new java.awt.Color(102, 0, 255));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        labeltab2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        labeltab2.setText("Dashboard");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(labeltab2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labeltab2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(tab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, 50));

        tab3.setBackground(new java.awt.Color(102, 0, 255));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        labeltab3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        labeltab3.setText("ATTENDANCE");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(labeltab3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labeltab3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(tab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, 50));

        tab5.setBackground(new java.awt.Color(102, 0, 255));
        tab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab5MouseClicked(evt);
            }
        });

        labeltab4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        labeltab4.setText("BORROWING");
        labeltab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltab4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab5Layout = new javax.swing.GroupLayout(tab5);
        tab5.setLayout(tab5Layout);
        tab5Layout.setHorizontalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(labeltab4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        tab5Layout.setVerticalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab5Layout.createSequentialGroup()
                .addComponent(labeltab4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel2.add(tab5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 220, 50));

        tab6.setBackground(new java.awt.Color(102, 0, 255));
        tab6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab6MouseClicked(evt);
            }
        });

        labeltab5.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        labeltab5.setText("LOG OUt");
        labeltab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeltab5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab6Layout = new javax.swing.GroupLayout(tab6);
        tab6.setLayout(tab6Layout);
        tab6Layout.setHorizontalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab6Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(labeltab5)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        tab6Layout.setVerticalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labeltab5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(tab6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 220, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 930));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1200));
        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        Borrowing.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("BORROWING");

        Inventory.setBackground(new java.awt.Color(255, 255, 255));
        Inventory.setPreferredSize(new java.awt.Dimension(1920, 1000));
        Inventory.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Inventory CRUD");
        Inventory.add(jLabel2);
        jLabel2.setBounds(50, 20, 420, 34);

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Category");
        Inventory.add(jLabel3);
        jLabel3.setBounds(80, 210, 145, 33);

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Equipment name");
        Inventory.add(jLabel5);
        jLabel5.setBounds(80, 110, 145, 33);

        EquipmentTf.setBackground(new java.awt.Color(255, 255, 255));
        Inventory.add(EquipmentTf);
        EquipmentTf.setBounds(80, 150, 220, 60);

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Quantity");
        Inventory.add(jLabel6);
        jLabel6.setBounds(80, 330, 145, 33);

        categoryCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "Biology", "Physics", "Chemistry", "Earth Science" }));
        Inventory.add(categoryCbx);
        categoryCbx.setBounds(80, 250, 220, 60);

        AddBtn.setBackground(new java.awt.Color(102, 0, 255));
        AddBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddBtn.setText("ADD");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        Inventory.add(AddBtn);
        AddBtn.setBounds(80, 480, 370, 70);

        UpdateBtn.setBackground(new java.awt.Color(102, 0, 255));
        UpdateBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        UpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBtn.setText("UPDATE");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        Inventory.add(UpdateBtn);
        UpdateBtn.setBounds(80, 560, 370, 70);

        DeleteBtn.setBackground(new java.awt.Color(102, 0, 255));
        DeleteBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setText("DELETE");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        Inventory.add(DeleteBtn);
        DeleteBtn.setBounds(80, 650, 370, 70);

        ClearBtn.setBackground(new java.awt.Color(102, 0, 255));
        ClearBtn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        ClearBtn.setForeground(new java.awt.Color(255, 255, 255));
        ClearBtn.setText("CLEAR");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });
        Inventory.add(ClearBtn);
        ClearBtn.setBounds(80, 730, 370, 70);

        InventoryTable.setBackground(new java.awt.Color(255, 255, 255));
        InventoryTable.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        InventoryTable.setForeground(new java.awt.Color(0, 0, 0));
        InventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Equipment", "Quantity", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        InventoryTable.setAlignmentX(1.0F);
        InventoryTable.setAlignmentY(1.0F);
        InventoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(InventoryTable);

        Inventory.add(jScrollPane1);
        jScrollPane1.setBounds(553, 30, 670, 660);
        Inventory.add(QuantityTf);
        QuantityTf.setBounds(80, 370, 220, 60);
        QuantityTf.setValue(1);

        idTxt.setBackground(new java.awt.Color(255, 255, 255));
        Inventory.add(idTxt);
        idTxt.setBounds(750, 280, 132, 30);
        idTxt.setEditable(false);

        javax.swing.GroupLayout BorrowingLayout = new javax.swing.GroupLayout(Borrowing);
        Borrowing.setLayout(BorrowingLayout);
        BorrowingLayout.setHorizontalGroup(
            BorrowingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorrowingLayout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BorrowingLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BorrowingLayout.setVerticalGroup(
            BorrowingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorrowingLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Borrowing);

        Attendance.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Attendance");

        javax.swing.GroupLayout AttendanceLayout = new javax.swing.GroupLayout(Attendance);
        Attendance.setLayout(AttendanceLayout);
        AttendanceLayout.setHorizontalGroup(
            AttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendanceLayout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(881, Short.MAX_VALUE))
        );
        AttendanceLayout.setVerticalGroup(
            AttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendanceLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(857, Short.MAX_VALUE))
        );

        jPanel1.add(Attendance);

        Dashboard.setBackground(new java.awt.Color(242, 242, 242));
        Dashboard.setMaximumSize(new java.awt.Dimension(1080, 1920));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ANALYTICS");

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        cards1.setColor1(new java.awt.Color(255, 51, 255));
        cards1.setColor2(new java.awt.Color(204, 0, 204));
        jPanel3.add(cards1);

        cards2.setColor1(new java.awt.Color(102, 153, 255));
        cards2.setColor2(new java.awt.Color(0, 51, 204));
        jPanel3.add(cards2);

        cards3.setColor1(new java.awt.Color(102, 255, 204));
        cards3.setColor2(new java.awt.Color(0, 153, 153));
        jPanel3.add(cards3);

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(521, Short.MAX_VALUE))
        );

        jPanel1.add(Dashboard);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1330, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        // TODO add your handling code here:\

        Inventory.setVisible(true);
        Dashboard.setVisible(false);
        Attendance.setVisible(false);
        Borrowing.setVisible(false);

        tab1.setBackground(new Color(204, 204, 255)); // 50% transparent white
        tab2.setBackground(new Color(102, 0, 255));
        tab3.setBackground(new Color(102, 0, 255));
        tab5.setBackground(new Color(102, 0, 255));

        labeltab1.setForeground(Color.black);
        labeltab2.setForeground(Color.white);
        labeltab3.setForeground(Color.white);
        labeltab4.setForeground(Color.white);


    }//GEN-LAST:event_tab1MouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        // TODO add your handling code here:

        Inventory.setVisible(false);
        Dashboard.setVisible(true);
        Attendance.setVisible(false);
        Borrowing.setVisible(false);

        tab2.setBackground(new Color(204, 204, 255)); // 50% transparent white
        tab1.setBackground(new Color(102, 0, 255));
        tab3.setBackground(new Color(102, 0, 255));
        tab5.setBackground(new Color(102, 0, 255));

        labeltab2.setForeground(Color.black);
        labeltab1.setForeground(Color.white);
        labeltab3.setForeground(Color.white);
        labeltab4.setForeground(Color.white);

    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        // TODO add your handling code here:

        Inventory.setVisible(false);
        Dashboard.setVisible(false);
        Attendance.setVisible(true);
        Borrowing.setVisible(false);

        tab3.setBackground(new Color(204, 204, 255)); // 50% trasnsparent white
        tab1.setBackground(new Color(102, 0, 255));
        tab2.setBackground(new Color(102, 0, 255));
        tab5.setBackground(new Color(102, 0, 255));

        labeltab3.setForeground(Color.black);
        labeltab2.setForeground(Color.white);
        labeltab1.setForeground(Color.white);
        labeltab4.setForeground(Color.white);

    }//GEN-LAST:event_tab3MouseClicked

    private void tab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab5MouseClicked
        // TODO add your handling code here:

        Inventory.setVisible(false);
        Dashboard.setVisible(false);
        Attendance.setVisible(false);
        Borrowing.setVisible(true);

        tab5.setBackground(new Color(204, 204, 255)); // 50% transparent white
        tab1.setBackground(new Color(102, 0, 255));
        tab2.setBackground(new Color(102, 0, 255));
        tab3.setBackground(new Color(102, 0, 255));

        labeltab4.setForeground(Color.black);
        labeltab2.setForeground(Color.white);
        labeltab1.setForeground(Color.white);
        labeltab3.setForeground(Color.white);
    }//GEN-LAST:event_tab5MouseClicked

    private void labeltab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltab4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labeltab4MouseClicked

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        String equipment_name = EquipmentTf.getText().toLowerCase();
        int quantity = (int) QuantityTf.getValue();
        String category = (String) categoryCbx.getSelectedItem();

        if (equipment_name == null || equipment_name.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the equipment name.");
            return;
        }
        if (quantity <= 0) {
            // Handle the case where the value is less than or equal to 0
            JOptionPane.showMessageDialog(null, "Please enter a valid number greater than 0.");
            return;
        }
        if (categoryCbx.getSelectedItem().equals("Select Category")) {
            JOptionPane.showMessageDialog(null, "Please Select an item");
            return;
        } else {
            InventoryHandler.AddInventory(equipment_name, quantity, category);

        }

        EquipmentTf.setText("");
        categoryCbx.setSelectedItem("Select Category");
        QuantityTf.setValue(1);

        // clear the table before add
        DefaultTableModel model = (DefaultTableModel) InventoryTable.getModel();
        model.setRowCount(0);

        // to update the table
        try (Connection conn = DatabaseConnector.getConnection()) {
            String query = "SELECT * FROM inventorytable";
            PreparedStatement pstmt = conn.prepareStatement(query);
            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                // User exists with the provided username and password
                String id = String.valueOf(rs.getInt("id"));
                String name = rs.getString("equipment_name");
                String category1 = rs.getString("category");
                String quantity1 = String.valueOf(rs.getInt("quantity"));

                //String array for store data into jtable
                String tbData[] = {id, name, quantity1, category1};

                DefaultTableModel tblModel = (DefaultTableModel) InventoryTable.getModel();

                //add Strinf array dara into table
                tblModel.addRow(tbData);

            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_AddBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            String id1 = idTxt.getText().toLowerCase();
            int id = Integer.parseInt(id1);
            String equipment = EquipmentTf.getText().toLowerCase();
            String category = (String) categoryCbx.getSelectedItem();
            int quantity = (int) QuantityTf.getValue();

            // contact number validator
            if (EquipmentTf.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "First name is empty.");
            }
            if (categoryCbx.getSelectedItem().equals("Select Category")) {
                JOptionPane.showMessageDialog(null, "Please Select an item");
                return;
            } else {
                InventoryHandler.UpdateInventory(id, equipment, quantity, category);
                JOptionPane.showMessageDialog(null, "Inventory updated");
            }

            idTxt.setText("");
            EquipmentTf.setText("");
            categoryCbx.setSelectedItem("Select category");
            QuantityTf.setValue(1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Complete the input");
        }

        // clear the table before add
        DefaultTableModel model = (DefaultTableModel) InventoryTable.getModel();
        model.setRowCount(0);

        // to update the table
        try (Connection conn = DatabaseConnector.getConnection()) {
            String query = "SELECT * FROM inventorytable";
            PreparedStatement pstmt = conn.prepareStatement(query);
            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                // User exists with the provided username and password
                String id = String.valueOf(rs.getInt("id"));
                String name = rs.getString("equipment_name");
                String category = rs.getString("category");
                String quantity = String.valueOf(rs.getInt("quantity"));

                //String array for store data into jtable
                String tbData[] = {id, name, quantity, category};

                DefaultTableModel tblModel = (DefaultTableModel) InventoryTable.getModel();

                //add Strinf array dara into table
                tblModel.addRow(tbData);

            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void labeltab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeltab5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labeltab5MouseClicked

    private void tab6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab6MouseClicked
        // TODO add your handling code here:
        dispose();
        Frontpage page = new Frontpage();
        page.setVisible(true);


    }//GEN-LAST:event_tab6MouseClicked

    private void InventoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryTableMouseClicked
        // TODO add your handling code here:
        int i = InventoryTable.getSelectedRow();
        TableModel model = InventoryTable.getModel();

        idTxt.setText(model.getValueAt(i, 0).toString());
        EquipmentTf.setText(model.getValueAt(i, 1).toString());
        // to get the data from the spinner
        String spinner = model.getValueAt(i, 2).toString();
        int spinner1 = Integer.parseInt(spinner);
        QuantityTf.setValue(spinner1);

        String equipment = model.getValueAt(i, 3).toString();
        for (int j = 0; j < categoryCbx.getItemCount(); j++) {
            if (categoryCbx.getItemAt(j).toString().equalsIgnoreCase(equipment)) {
                categoryCbx.setSelectedIndex(j);
            }
        }

    }//GEN-LAST:event_InventoryTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JPanel Attendance;
    private javax.swing.JPanel Borrowing;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField EquipmentTf;
    private javax.swing.JPanel Inventory;
    private javax.swing.JTable InventoryTable;
    private javax.swing.JSpinner QuantityTf;
    private javax.swing.JButton UpdateBtn;
    private com.CustomCards.Cards cards1;
    private com.CustomCards.Cards cards2;
    private com.CustomCards.Cards cards3;
    private javax.swing.JComboBox<String> categoryCbx;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labeltab1;
    private javax.swing.JLabel labeltab2;
    private javax.swing.JLabel labeltab3;
    private javax.swing.JLabel labeltab4;
    private javax.swing.JLabel labeltab5;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab5;
    private javax.swing.JPanel tab6;
    // End of variables declaration//GEN-END:variables
}
